services:
  # Backend API Service (Development)
  backend:
    build: 
      context: ./back-end
      dockerfile: Dockerfile
    container_name: ecommerce-backend-dev
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - SESSION_SECRET=development-session-secret
    volumes:
      # Mount source code for hot reload
      - ./back-end:/app
      - /app/node_modules
      # Mount data directory for persistent JSON storage
      - backend_data_dev:/app/data
      # Mount images directory for persistent image storage
      - backend_images_dev:/app/public/images
    networks:
      - ecommerce-network-dev
    restart: unless-stopped
    command: npm run dev

  # Frontend Service (Development)
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile.dev
    container_name: ecommerce-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5000/api
    volumes:
      # Mount source code for hot reload
      - ./front-end:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - ecommerce-network-dev
    restart: unless-stopped
    command: npm run dev -- --host 0.0.0.0

# Named volumes for persistent data
volumes:
  backend_data_dev:
    driver: local
  backend_images_dev:
    driver: local

# Custom network for service communication
networks:
  ecommerce-network-dev:
    driver: bridge
